### ISSUE TITLE
OTClient doesn't start on latest Windows 10 pro build

### ISSUE THREAD

**Issue by tarantonio** [otland/otclient#20]
I compiled OTClient in Visual Studio 2017 with vcpkg method, Release x64.

On Windows 10 pro version 1809, build 17763.316 exe doesn't start.
I tried the same exe on another pc with version 1803, build 17134.590 and exe starts without problem.

**Comment by BahamutxD** [comment]
No issue here/can't reproduce. Same OS, VS17 and compiled OTC in 32bit.

**Comment by tarantonio** [comment]
> No issue here/can't reproduce. Same OS, VS17 and compiled OTC in 32bit. Could Windows antivirus be blocking/scanning OTC .exe?

Can you zip and post here your exe+dll?

**Comment by EgzoT** [comment]
Maybe you use (copy) wrong libs, for example 64 bit instead 32 bit, or debug instead normal?

**Comment by tarantonio** [comment]
I uses the vcpkg vs 2017 method, release x64, the same exe on previous builds of windows start without problem, it’s only on that build I posted before that doesn’t work

**Comment by DSpeichert** [comment]
I have similar problem where builds from AppVeyor don't work for me on `Windows 10 pro version 1809, build 17763.316` but built locally do.

**Comment by tarantonio** [comment]
I also compiled otclient in release x86 and doesn't start. I tried the same exe on another build of windows and starts normally

**Comment by GustavoContreiras** [comment]
Try reinstall https://www.microsoft.com/en-us/download/details.aspx?id=48145

The Visual C++ Redistributable Packages install run-time components of Visual C++ libraries. These components are required to run C++ applications that are developed using Visual Studio 2015 and link dynamically to Visual C++ libraries. These package can be used to run such applications on a computer even if it does not have Visual Studio 2015 installed. These packages install run-time components of these libraries: C Runtime (CRT), Standard C++, MFC, C++ AMP, and OpenMP.

**Comment by tarantonio** [comment]
> Try reinstall https://www.microsoft.com/en-us/download/details.aspx?id=48145
> 
> The Visual C++ Redistributable Packages install run-time components of Visual C++ libraries. These components are required to run C++ applications that are developed using Visual Studio 2015 and link dynamically to Visual C++ libraries. These package can be used to run such applications on a computer even if it does not have Visual Studio 2015 installed. These packages install run-time components of these libraries: C Runtime (CRT), Standard C++, MFC, C++ AMP, and OpenMP.

I have installed those libraries:
![y5up7kq](https://user-images.githubusercontent.com/7066891/53695968-722cd000-3dc2-11e9-9ecc-3654aee229a6.png)

**Comment by tarantonio** [comment]
> I have similar problem where builds from AppVeyor don't work for me on `Windows 10 pro version 1809, build 17763.316` but built locally do.

How did you compile it?

**Comment by tarantonio** [comment]
I made some experiments:

- I compiled OTClient on a pc with version 1803, build 17134.590 => starts normally on that PC, doesn't start on version 1809, build 17763.316
- I compiled OTClient on a pc with version 1809, build 17763.316 => starts normally on that PC, doesn't start on version 1809, build 17763.316

So I think the problem is more on the windows build side, and maybe related to some dll problem with it.

**Comment by tarantonio** [comment]
Problem persists on today's update of windows:
![vdl1krd](https://user-images.githubusercontent.com/7066891/53795741-e4242700-3f32-11e9-9454-9ea7f26e08ec.png)

**Comment by tarantonio** [comment]
On OTLand @kondra found the fix for that.
The reason was that visual studio had AVX2 processor extension enabled by default while my cpu was not supporting it. I've changed it to SSE2 and it worked
![otc](https://user-images.githubusercontent.com/7066891/53874835-8f9cac80-4003-11e9-9d4e-bd0a297d4f67.PNG)
In my case, Release x64, I had to disable that option.

**Comment by tarantonio** [comment]
The issue was VS related. Change the processor extension on project as required.

**Comment by DSpeichert** [comment]
This isn't a proper "fix".
The master branch does not have AVX2 enabled by default - it has AVX, which is available on most processors.

**Comment by tarantonio** [comment]
> This isn't a proper "fix".
> The master branch does not have AVX2 enabled by default - it has AVX, which is available on most processors.

It's neccesary to enable that option? I had to disable to make it work on my PC with x64 Release mode.

**Comment by DSpeichert** [comment]
No, it *may* make some code faster by using AVX(2) processor instructions but it's not required.
