### ISSUE TITLE
Resize configuration window

### ISSUE THREAD

**Issue by GustavoContreiras** [otland/otclient#23]
**Describe the bug**
The size of the config window is wrong.

**To Reproduce**
1. Open client
2. Go to configs

**Expected behavior**
Buttons showing correctly at the bottom of the config window.

**Additional context**
This bug was introduced with this commit https://github.com/otland/otclient/commit/d291c7c34e022549ac0d51a471f0795ab410cda6

**Comment by EgzoT** [comment]
Maybe you add screenshot?

**Comment by EgzoT** [comment]
My proposition is bit another, we may add new panel in options named "Panel" with options for panels. Probably in future we add new panels features so we will don't must resize it in all time when we will want to add new option.
