### ISSUE TITLE
[Question] loadXml function

### ISSUE THREAD

**Issue by GustavoContreiras** [otland/otclient#29]
Shouldn't this function be loadItemsXml? I tried to load a xml file and then I found that this function is just for the items.xml file.

**Comment by EgzoT** [comment]
This function load items.xml (server side ids).
Some functions use it, like getClientId() etc.

**Comment by DSpeichert** [comment]
It probably should, do you want to PR a rename? @GustavoContreiras

**Comment by GustavoContreiras** [comment]
I dont want but is there any problem in making a commit for rename? Didnt know that

**Comment by GustavoContreiras** [comment]
Nah, just warning, if somebody want go ahead

**Comment by EgzoT** [comment]
In that case we lost backward compatible with some modules.
