### ISSUE TITLE
AppVeyor build artifacts can't launch on Windows 10's 1809 update

### ISSUE THREAD

**Issue by Sickness-chan** [otland/otclient#39]
**Describe the bug**
Windows 10's 1809 update introduced a bug to PhysFS, which in turn prevents OTC from starting up correctly as it can't find files or directories properly. Physfs has already fixed the issue, but the build artifacts on AppVeyor do not seem to have an updated PhysFS version, hence you can't launch the client if you run a version of Windows 10 that is 1809 or newer. To resolve this, you'd somehow need to get AppVeyor to pull the latest PhysFS version from vcpkg, and it should be resolved, as I suspect it's currently using an older cached version.

This is the commit to vcpkg that fixes the issue: https://github.com/Microsoft/vcpkg/commit/1225d80d11124aaa0be7f437772c1b3b9db5efc1

**To Reproduce**
1. Install the Windows 10 1809 update or newer (can be checked with winver)
2. Download the latest .zip artifacts from AppVeyor
3. Try to launch otclient.exe

**Expected behavior**
OTC starts normally

**Environment**
1. Latest AppVeyor OTC build
2. Windows 10 Version 1809 (Build 17763.529)

**Comment by DSpeichert** [comment]
They builds work on Wind 10 1903. I don't know what was changed but it "magically" started to work again.

**Comment by Sickness-chan** [comment]
I'm still on 1809 and it was still broken on the latest build that I tried 5 hours ago. Even if updating Windows fixes it again, we should look for a way to update the PhysFS version that AppVeyor currently uses. That way, both 1809 and 1903 would work fine.

**Comment by DSpeichert** [comment]
Last time I investigated that, I came to the conclusion that vcpkg does ship latest version and I did clean the AppVeyor cache at that time. I can try that again.

**Comment by DSpeichert** [comment]
@Sickness-chan Try now, it's a fresh build with cleared cache.

**Comment by Sickness-chan** [comment]
It works now, thanks.
